apiVersion: v1
kind: Service
metadata:
  name: repo-intel-api-service
  namespace: repo-intel
spec:
  type: ClusterIP
  selector:
    app: repo-intel-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
