import type {
  AIProvider,
  AIChatOptions,
  AIChatResponse,
  AIStreamChunk,
  ProviderHealthStatus,
  ModelCapabilities,
} from '@repo-intel/shared';

export class MockAIProvider implements AIProvider {
  constructor(
    private readonly name = 'mock',
    private readonly modelName = 'mock-gpt-4o',
  ) {}

  public async chat(prompt: string, options?: AIChatOptions): Promise<AIChatResponse> {
    const isJson = options?.responseFormat === 'json';

    let content = `Mock AI response for query: ${prompt.substring(0, 50)}...`;
    if (isJson) {
      content = JSON.stringify({
        findings: [
          {
            title: 'Mock Issue Detected',
            description: `Mock analysis result for ${prompt.substring(0, 40)}`,
            severity: 'medium',
            confidence: 0.9,
            explanation: 'Generated by MockAIProvider for offline testing.',
            recommendation: 'Verify input parameters.',
          },
        ],
      });
    }

    return {
      content,
      provider: this.name,
      model: options?.model ?? this.modelName,
      usage: {
        promptTokens: prompt.length / 4,
        completionTokens: content.length / 4,
        totalTokens: (prompt.length + content.length) / 4,
      },
      durationMs: 15,
    };
  }

  public async *stream(prompt: string, options?: AIChatOptions): AsyncIterable<AIStreamChunk> {
    const res = await this.chat(prompt, options);
    const words = res.content.split(' ');
    for (const word of words) {
      yield { delta: `${word} `, isComplete: false };
    }
    yield { delta: '', isComplete: true };
  }

  public async embeddings(texts: string[]): Promise<number[][]> {
    return texts.map((text) => {
      const vec = new Array<number>(128).fill(0);
      for (let i = 0; i < text.length; i++) {
        const charCode = text.charCodeAt(i);
        const curr = vec[i % 128] ?? 0;
        vec[i % 128] = curr + charCode / 255;
      }
      return vec;
    });
  }

  public async health(): Promise<ProviderHealthStatus> {
    return {
      provider: this.name,
      isAvailable: true,
      latencyMs: 5,
    };
  }

  public metadata(): ModelCapabilities {
    return {
      provider: this.name,
      model: this.modelName,
      contextWindow: 128000,
      pricingPer1kInput: 0,
      pricingPer1kOutput: 0,
      supportsReasoning: true,
      supportsTools: true,
      supportsStreaming: true,
      supportsVision: false,
    };
  }
}
